namespace CleanExtract.Core.Config;

/// <summary>
/// Conservative domain lists. Blocked domains stay empty unless the user adds them.
/// Trusted domains are well-known documentation / source hosts, not a web-wide allowlist.
/// Suspicious domains are URL shorteners: they add score, they never auto-delete by themselves.
/// </summary>
public static class DomainCatalog
{
    public static IReadOnlyList<string> DefaultTrusted { get; } =
    [
        "github.com",
        "githubusercontent.com",
        "gitlab.com",
        "bitbucket.org",
        "codeberg.org",
        "sourceforge.net",
        "git-scm.com",
        "kernel.org",
        "gnu.org",
        "fsf.org",
        "wikipedia.org",
        "wikimedia.org",
        "archive.org",
        "python.org",
        "pypi.org",
        "pythonhosted.org",
        "rust-lang.org",
        "crates.io",
        "docs.rs",
        "golang.org",
        "go.dev",
        "nodejs.org",
        "npmjs.com",
        "nuget.org",
        "microsoft.com",
        "learn.microsoft.com",
        "visualstudio.com",
        "dot.net",
        "mozilla.org",
        "firefox.com",
        "developer.mozilla.org",
        "apple.com",
        "developer.apple.com",
        "videolan.org",
        "7-zip.org",
        "gitbook.io",
        "readthedocs.io",
        "readthedocs.org",
        "stackoverflow.com",
        "stackexchange.com",
        "superuser.com",
        "serverfault.com",
        "godotengine.org",
        "unity.com",
        "unrealengine.com",
        "itch.io",
        "libsdl.org",
        "opengl.org",
        "khronos.org",
        "iana.org",
        "ietf.org",
        "w3.org",
        "rfc-editor.org",
        "creativecommons.org",
        "opensource.org",
        "apache.org",
        "debian.org",
        "ubuntu.com",
        "llvm.org",
        "cmake.org",
        "sqlite.org",
        "postgresql.org",
        "mysql.com",
        "mariadb.org",
        "redis.io",
        "docker.com",
        "kubernetes.io",
        "cncf.io",
    ];

    public static IReadOnlyList<string> DefaultSuspicious { get; } =
    [
        "bit.ly",
        "tinyurl.com",
        "tiny.cc",
        "t.co",
        "cutt.ly",
        "shorturl.at",
        "is.gd",
        "ow.ly",
        "rebrand.ly",
        "s.id",
        "rb.gy",
        "short.gy",
    ];
}
